"""empty message

Revision ID: 48874334fd9f
Revises: 6fc818f0eb4d
Create Date: 2021-07-05 01:14:36.707019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48874334fd9f'
down_revision = '6fc818f0eb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, primary_key= True))
    # ### end Alembic commands ###
